### ISSUE TITLE
impersonators on Disqus sites

### ISSUE THREAD

**Issue by JeffersonWood** [fizbin/killfile-extension#1]
Really impressed and pleased with the extension, I noticed, however that it doesn't handle impersonators on Disqus forums well. Looks like you're using the user's name to identify a 'hushed' poster, but abusers on that forum often spoof the names of legit users.  Why not use the 'data-username' attribute instead?

**Comment by fizbin** [comment]
Huh - I hadn't noticed that property. Yeah, I'll switch to using that to identify users. I just first need to work out a transition plan...

**Comment by JeffersonWood** [comment]
I was fiddling with some similar code a while back, but other work got in the way. One thing I noticed about that attribute is that on at least one occasion it was blank. I suspect the spammer had registered using special characters, or a line-feed code or something like that, so that it would break the disqus template. It may be that an option to 'hush' people with a missing or malformed 'data-username' would defeat the more clever spammers.
Again, thanks for your work.

**Comment by fizbin** [comment]
Presumably, if I base blocking around that property, the first such clever spammer hushed will cause all similar spammers with blank data-username to also be hushed.

**Comment by JeffersonWood** [comment]
I guess your right about that.

**Comment by Wirone** [comment]
Any news about it? I started using your extension today and also was surprised you're not using `data-username` attribute.

**Comment by fizbin** [comment]
Okay, having now gotten around to looking at it in detail, it seems that I did actually use the disqus attribute, but at some point it changed from being `data-user` to being `data-username`, and that meant that I lost the per-disqus-id tracking. Well, that and I had a bug in my regex that meant I had trouble matching attributes properly in any case.

Fix should be on its way.

**Comment by fizbin** [comment]
Version 0.2.7 is up for Google Chrome and Firefox that should resolve this; however, as I don't regularly visit sites with name-changing trolls like this, I may not fully understand the problem or the desired solution. Do you have an example of a discussion where this would have been useful?

**Comment by Wirone** [comment]
Is `data-username` really used? I looked into Disqus thread and I see that under `dtm_killfile_user` display names are stored, not real user names.

Like [here](http://darekwolowski.blox.pl/2015/12/Gorzej-juz-byc-nie-moze.html#comment-2393817243):
- `data-username` is `disqus_EUgvSrERxV`
- display name and `dtm_killfile_user` (at `commenttopxpath`) is `mr.nobody`

If 2 different people have the same display name, would Killfile hush them both?

**Comment by fizbin** [comment]
Are you sure you're using the latest version of killfile? (0.2.7)

I look there, and see:

```
<div data-role="post-content" class="post-content dtm_killfile_commentholder target dtm_killfile_commentholder_showcomment" dtm_killfile_user="mr.nobody!disqus_EUgvSrERxV">
```

So `data-username` is used exactly as "url" is in many of the other blog scenarios.

**Comment by Wirone** [comment]
Ah, my fault. I had my local version enabled, not official from Extensions Repository, and it was not up to date. I checked again and yes, I see `dtm_killfile_user="mr.nobody!disqus_EUgvSrERxV"`. Seems good.
