### ISSUE TITLE
Extension for Opera

### ISSUE THREAD

**Issue by Wirone** [fizbin/killfile-extension#4]
Since Opera is based on Chromium Killfile extension for Chrome works there like a charm. I have tested it with manual installation with my forked version - works witk Disqus and Blox comments.

Only thing to do is add extension to official repository, so Opera users could install it from [extensions page](https://addons.opera.com/pl/extensions/).

**Comment by fizbin** [comment]
Version 0.2.7 has been submitted to Opera. We'll see what happens.

**Comment by fizbin** [comment]
https://addons.opera.com/en/extensions/details/blog-comment-killfile/?display=en
